/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-17 03:21:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.myCourse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;
import user.model.vo.User;

public final class myCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/myCourse/../common/footer.jsp", Long.valueOf(1568176001819L));
    _jspx_dependants.put("/views/myCourse/../common/gnb.jsp", Long.valueOf(1568653623588L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/vendors/css/normalize.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/vendors/css/bootstrap-grid.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/vendors/css/bootstrap.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,300,300i,400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/resources/css/common/gnb.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/resources/css/common/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/testt/resources/css/queries.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/myCourse.css\">\r\n");
      out.write("\r\n");
      out.write("<title>탈무브 | 내 강좌</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	User loginUser = (User)session.getAttribute("loginUser");
	String message = (String)session.getAttribute("message");
	if(message != null){

      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">alert(\"");
      out.print( message );
      out.write("\")</script>\r\n");

	session.removeAttribute("message");}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<header>\r\n");
      out.write("        <nav>\r\n");
      out.write("           <div id=\"menuToggle\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"togglechk\">\r\n");
      out.write("                <div class=\"toggle-back\"></div>\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("\r\n");
      out.write("                <ul id=\"menu\">\r\n");
      out.write("                \t");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("                    <a href=\"/testt/views/loginEnroll/login.jsp\"><li>로그인</li></a>\r\n");
      out.write("                    <a href=\"#\"><li>회원가입</li></a>\r\n");
      out.write("                    <a href=\"/testt/views/courseOpen/courseOpen.jsp\"><li>강좌개설</li></a>\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    <a href=\"/testt/views/mypage/UserUpdateView.jsp\"><li>");
      out.print( loginUser.getUserName() );
      out.write("</li></a>\r\n");
      out.write("                    <a href=\"/testt/views/myCourse/myCourse.jsp\"><li>내강좌</li></a>\r\n");
      out.write("                    <a href=\"#\"><li>장바구니</li></a>\r\n");
      out.write("                    <a href=\"/testt/views/courseOpen/courseOpen.jsp\"><li>강좌개설</li></a>\r\n");
      out.write("                    <a href=\"/testt/logout\"><li>로그아웃</li></a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <li>카테고리</li>\r\n");
      out.write("                    <a onclick=\"setTimeout(toggleList('business'),200);\"><li>비즈니스<i id=\"business-list\" class=\"fa fa-chevron-down list-down\"></i></li></a>\r\n");
      out.write("                    <ul class=\"toggle-business\">\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='비즈니스'\"><li>비즈니스 전체보기</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='커뮤니케이션'\"><li>커뮤니케이션</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='경영'\"><li>경영</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='판매'\"><li>판매</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='전략'\"><li>전략</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='운영'\"><li>운영</li></a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a onclick=\"toggleList('programming');\"><li>프로그래밍<i id =\"programming-list\" class=\"fa fa-chevron-down list-down\"></i></li></a>\r\n");
      out.write("                    <ul class=\"toggle-programming\">\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='프로그래밍'\"><li>프로그래밍 전체보기</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='프로그래밍 이론'\"><li>프로그래밍 이론</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='프로그래밍 언어'\"><li>프로그래밍 언어</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='웹'\"><li>웹</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='모바일'\"><li>모바일</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='게임'\"><li>게임</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='DB'\"><li>DB</li></a>\r\n");
      out.write("                        <a href=\"/testt/views/category/categoryDetail.jsp?category='데이터과학'\"><li>데이터과학</li></a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"gnb-logo\">\r\n");
      out.write("                    <p class=\"logo-text\"><a href=\"/testt/index.jsp\">TALMOVE</a></p>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <p class=\"category dropbtn\">카테고리</p>\r\n");
      out.write("                        <div class=\"dropdown-content\">\r\n");
      out.write("                            <a id=\"business\" href=\"#\">비즈니스</a>\r\n");
      out.write("                            <a id=\"programming\" href=\"#\">프로그래밍</a>\r\n");
      out.write("                            <div class=\"dropdown-contentSub\">\r\n");
      out.write("                                <div class=\"is-visible drop-business\">\r\n");
      out.write("                                    <a href=\"/testt/views/category/categoryDetail.jsp?category='비즈니스'\">비즈니스 전체보기</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='커뮤니케이션'\">커뮤니케이션</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='경영'\">경영</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='판매'\">판매</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='전략'\">전략</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='운영'\">운영</a>    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"drop-programming\">\r\n");
      out.write("                                    <a href=\"/testt/views/category/categoryDetail.jsp?category='프로그래밍'\">프로그래밍 전체보기</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='프로그래밍 이론'\">프로그래밍 이론</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='프로그래밍 언어'\">프로그래밍 언어</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='웹'\">웹</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='모바일'\">모바일</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='게임'\">게임</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='DB'\">DB</a>\r\n");
      out.write("\t\t\t                        <a href=\"/testt/views/category/categoryDetail.jsp?category='데이터과학'\">데이터과학</a> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"gnb-search\">\r\n");
      out.write("                    <form action=\"\">\r\n");
      out.write("                        <input type=\"search\" placeholder=\"검색\" maxlength=\"30\">\r\n");
      out.write("                        <button><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"gnb-unlogin-nav\">\r\n");
      out.write("                ");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("                \t<ul class=\"unlogin-nav\">\r\n");
      out.write("                        <li><button onclick=\"location.href='/testt/views/courseOpen/courseOpen.jsp'\">강좌개설</button></li>\r\n");
      out.write("                        <li><button id=\"login-btn\">로그인</button></li>\r\n");
      out.write("                        <li><button id=\"signup-btn\">회원가입</button></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 }else{ 
      out.write("\r\n");
      out.write("                \t<ul class=\"unlogin-nav\">\r\n");
      out.write("                        <li><button onclick=\"location.href='/testt/views/courseOpen/courseOpen.jsp'\">강좌개설</button></li>\r\n");
      out.write("                        <li><button onclick=\"location.href='/testt/views/myCourse/myCourse.jsp'\">내강좌</button></li>\r\n");
      out.write("                        <li><button>장바구니</button></li>\r\n");
      out.write("                        <div class=\"mydrop\">\r\n");
      out.write("                            <li><button>");
      out.print( loginUser.getUserName() );
      out.write("</button></li>\r\n");
      out.write("                            <div class=\"mydrop-content\">\r\n");
      out.write("                                <a href=\"/testt/views/mypage/UserUpdateView.jsp\"><i class=\"fas fa-user-circle\"></i>프로필</a>\r\n");
      out.write("                                <a href=\"/testt/views/mypage/MessageListView.jsp\"><i class=\"far fa-envelope\"></i>메시지</a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"far fa-credit-card\"></i>결제내역</a>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <a href=\"/testt/logout\"><i class=\"fa fa-sign-out-alt\"></i>로그아웃</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </div>        \r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"enroll-form\" class=\"modal-form\">\r\n");
      out.write("            <div class=\"modal-form-content\">\r\n");
      out.write("                <div class=\"form-nav\">\r\n");
      out.write("                   <button id=\"login-tab\" class=\"form-tab\" onclick=\"changeTab('form-login', 'login-tab')\">로그인</button>\r\n");
      out.write("                   <button id=\"signup-tab\" class=\"form-tab\" onclick=\"changeTab('form-signup', 'signup-tab')\">회원가입</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-content\" id=\"form-login\">\r\n");
      out.write("                    <button id=\"api-login\"><img src=\"/testt/resources/img/google_logo.png\" alt=\"\">Google로 로그인</button>\r\n");
      out.write("                    <hr><p id=\"center-word\">또는</p><hr>\r\n");
      out.write("                    \r\n");
      out.write("                    <form action=\"/testt/login.ed\" method=\"post\" id=\"login-form\">\r\n");
      out.write("                        <p class=\"placeholder\" id=\"login-email-placeholder\">이메일</p>\r\n");
      out.write("                        <input type=\"text\" id=\"login-email\" name=\"uemail\" autocomplete=off required>\r\n");
      out.write("                        <p class=\"guide\" id=\"login-email-focus\">등록한 이메일 주소를 입력해주세요</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"login-pwd-placeholder\">비밀번호</p>\r\n");
      out.write("                        <input type=\"password\" id=\"login-pwd\" name=\"upwd\" required>\r\n");
      out.write("                        <p class=\"guide\" id=\"login-pwd-focus\">6자 이상, 20자 미만으로 입력해주세요</p>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"form-btn login-btn\" type=\"submit\">이메일로 로그인</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <a href=\"/testt/views/findpwd/findpwd.jsp\">비밀번호를 잊어버렸어요.</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-content\" id=\"form-signup\" style=\"display: none\">\r\n");
      out.write("                    <form action=\"/testt/enroll.ed\" method=\"post\">\r\n");
      out.write("                        <p class=\"placeholder\" id=\"email-placeholder\">이메일</p>\r\n");
      out.write("                        <input type=\"text\" name=\"uemail\" id=\"signup-email\" autocomplete=off required>\r\n");
      out.write("                        <p class=\"guide\" id=\"email-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"pwd-placeholder\">비밀번호</p>\r\n");
      out.write("                        <input type=\"password\" name=\"upwd\" id=\"signup-pwd\" required>\r\n");
      out.write("                        <p class=\"guide\" id=\"pwd-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"pwdchk-placeholder\">비밀번호 확인</p>\r\n");
      out.write("                        <input type=\"password\" id=\"signup-pwdchk\" required>\r\n");
      out.write("                        <p class=\"guide\" id=\"pwdchk-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"name-placeholder\">이름(실명)</p>\r\n");
      out.write("                        <input type=\"text\" name=\"uname\" id=\"signup-name\" autocomplete=off required>\r\n");
      out.write("                        <p class=\"guide\" id=\"name-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"form-btn enroll-btn\" type=\"submit\">이메일로 회원가입</button>\r\n");
      out.write("                        <p>회원가입 시, <a href=\"#\">탈무브 이용약관</a>, <a href=\"#\">개인정보 취급방침</a> 및 <a href=\"#\">개인정보 3자 제공</a>에 동의하게 됩니다.</p>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron jumbotron-fluid\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"display-7\">강의 듣기</h1>\r\n");
      out.write("\t\t\t<h2 class=\"display-7\">내 강좌</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- 첫째줄4개 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> \r\n");
      out.write("\t\t\t\t\t\t\t완료 \r\n");
      out.write("\t\t\t\t\t\t\t<span class='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> 완료 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> 완료 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> 완료 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /첫쨰줄 4개 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 둘쨰줄 4개 -->\r\n");
      out.write("\t\t<div class=\"row mb-5\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> 완료 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> 완료 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-lg-3 mt-4\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"card-img-top\"src=\"https://picsum.photos/200/150/?random\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/testt/views/coursePlay/coursePlay.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">자바 java 8 프로그래밍 중고급 배우기[2단계] 강좌</h4>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"name\">장관익</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress\" style=\"height: 10px;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" progress-bar\" role=\"progressbar\" style=\"width: 40%;\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='small course-progress-percentage'>\r\n");
      out.write("\t\t\t\t\t\t\t<span class='percentage'>40%</span> 완료 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass='float-right rating'>★★★★★</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"meta\" id=\"open-review-box\" style=\"text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">등급 남기기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /둘째줄 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 리뷰 모달 -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\t\taria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">×</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 align=\"center\">이 과정을 어떻게 평가합니까?</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"example\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<textarea></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">Save\r\n");
      out.write("\t\t\t\t\t\t\tchanges</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /리뷰 모달 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t    <div class=\"footer-container pt-2\">\r\n");
      out.write("\t        <div class=\"row footer-top\">\r\n");
      out.write("\t            <div class=\"col-12 col-md-6 footer-top-left\">\r\n");
      out.write("\t                <p class=\"logo-text\">TALMOVE</p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"col-6 col-md-6 footer-top-right\">\r\n");
      out.write("\t                <ul class=\"footer-nav mt-3\">\r\n");
      out.write("\t                    <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"row footer-middle mt-4\">\r\n");
      out.write("\t            <p class=\"col-sm-12\">서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층, 3층, 4층<br>010-1234-5678</p>\r\n");
      out.write("\t            \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"row footer-bottom\">\r\n");
      out.write("\t            <p class=\"col-sm-12\">Copyright &copy; 2019 by TALMOVE. All rights reserved.</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("    \r\n");
      out.write("    <button onclick=\"setTimeout(topFunction(), 200);\" id=\"topBtn\" title=\"Go to Top\"><i class=\"fas fa-chevron-up\"></i></button>");
      out.write("\r\n");
      out.write("\t<script src=\"/testt/vendors/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"/testt/vendors/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://kit.fontawesome.com/08d0951667.js\"></script>\r\n");
      out.write("\t<script src=\"/testt/resources/js/main.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#example').barrating({\r\n");
      out.write("\t\t\t\ttheme : 'css-stars'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
