/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-09 13:11:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/gnb.jsp", Long.valueOf(1568034376451L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1567516672911L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width:device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendors/css/normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendors/css/bootstrap-grid.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Lato:100,300,300i,400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/common/gnb.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/common/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/queries.css\">\r\n");
      out.write("    \r\n");
      out.write("    <title>탈무브 | 당신의 재능을 공유해주세요</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/08d0951667.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

	User loginUser = (User)session.getAttribute("loginUser");
	String message = (String)session.getAttribute("message");
	if(message != null){

      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">alert(\"");
      out.print( message );
      out.write("\")</script>\r\n");

	session.removeAttribute("message");}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<header>\r\n");
      out.write("        <nav>\r\n");
      out.write("           <div id=\"menuToggle\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"togglechk\">\r\n");
      out.write("                <div class=\"toggle-back\"></div>\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("\r\n");
      out.write("                <ul id=\"menu\">\r\n");
      out.write("                \t");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("                    <a href=\"/testt/views/loginEnroll/login.jsp\"><li>로그인</li></a>\r\n");
      out.write("                    <a href=\"#\"><li>회원가입</li></a>\r\n");
      out.write("                    <a href=\"/testt/views/courseOpen/courseOpen.jsp\"><li>강좌개설</li></a>\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    <a href=\"#\"><li>");
      out.print( loginUser.getUserName() );
      out.write("</li></a>\r\n");
      out.write("                    <a href=\"#\"><li>내강좌</li></a>\r\n");
      out.write("                    <a href=\"#\"><li>장바구니</li></a>\r\n");
      out.write("                    <a href=\"/testt/views/courseOpen/courseOpen.jsp\"><li>강좌개설</li></a>\r\n");
      out.write("                    <a href=\"/testt/logout\"><li>로그아웃</li></a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <li>카테고리</li>\r\n");
      out.write("                    <a onclick=\"setTimeout(toggleList('business'),200);\"><li>비즈니스<i id=\"business-list\" class=\"fa fa-chevron-down list-down\"></i></li></a>\r\n");
      out.write("                    <ul class=\"toggle-business\">\r\n");
      out.write("                        <a href=\"#\"><li>비즈니스 전체보기</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>커뮤니케이션</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>경영</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>판매</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>전략</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>운영</li></a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a onclick=\"toggleList('programming');\"><li>프로그래밍<i id =\"programming-list\" class=\"fa fa-chevron-down list-down\"></i></li></a>\r\n");
      out.write("                    <ul class=\"toggle-programming\">\r\n");
      out.write("                        <a href=\"#\"><li>프로그래밍 전체보기</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>프로그래밍 이론</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>프로그래밍 언어</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>웹</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>모바일</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>게임</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>DB</li></a>\r\n");
      out.write("                        <a href=\"#\"><li>데이터과학</li></a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"gnb-logo\">\r\n");
      out.write("                    <p class=\"logo-text\"><a href=\"/testt/index.jsp\">TALMOVE</a></p>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <p class=\"category btn btn-full dropbtn\">카테고리</p>\r\n");
      out.write("                        <div class=\"dropdown-content\">\r\n");
      out.write("                            <a id=\"business\" href=\"#\">비즈니스</a>\r\n");
      out.write("                            <a id=\"programming\" href=\"#\">프로그래밍</a>\r\n");
      out.write("                            <div class=\"dropdown-contentSub\">\r\n");
      out.write("                                <div class=\"is-visible drop-business\">\r\n");
      out.write("                                    <a href=\"#\">비즈니스 전체보기</a>\r\n");
      out.write("                                    <a href=\"#\">커뮤니케이션</a>\r\n");
      out.write("                                    <a href=\"#\">경영</a>\r\n");
      out.write("                                    <a href=\"#\">판매</a>\r\n");
      out.write("                                    <a href=\"#\">전략</a>\r\n");
      out.write("                                    <a href=\"#\">운영</a>    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"drop-programming\">\r\n");
      out.write("                                    <a href=\"#\">프로그래밍 전체보기</a>\r\n");
      out.write("                                    <a href=\"#\">프로그래밍 이론</a>\r\n");
      out.write("                                    <a href=\"#\">프로그래밍 언어</a>\r\n");
      out.write("                                    <a href=\"#\">웹</a>\r\n");
      out.write("                                    <a href=\"#\">모바일</a>\r\n");
      out.write("                                    <a href=\"#\">게임</a>    \r\n");
      out.write("                                    <a href=\"#\">DB</a>    \r\n");
      out.write("                                    <a href=\"#\">데이터과학</a>    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"gnb-search\">\r\n");
      out.write("                    <form action=\"\">\r\n");
      out.write("                        <input type=\"search\" placeholder=\"검색\" maxlength=\"30\">\r\n");
      out.write("                        <button><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"gnb-unlogin-nav\">\r\n");
      out.write("                ");
 if(loginUser == null){ 
      out.write("\r\n");
      out.write("                \t<ul class=\"unlogin-nav\">\r\n");
      out.write("                        <li><button onclick=\"location.href='/testt/views/courseOpen/courseOpen.jsp'\">강좌개설</button></li>\r\n");
      out.write("                        <li><button id=\"login-btn\">로그인</button></li>\r\n");
      out.write("                        <li><button id=\"signup-btn\">회원가입</button></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 }else{ 
      out.write("\r\n");
      out.write("                \t<ul class=\"unlogin-nav\">\r\n");
      out.write("                        <li><button onclick=\"location.href='/testt/views/courseOpen/courseOpen.jsp'\">강좌개설</button></li>\r\n");
      out.write("                        <li><button>내강좌</button></li>\r\n");
      out.write("                        <li><button>장바구니</button></li>\r\n");
      out.write("                        <div class=\"mydrop\">\r\n");
      out.write("                            <li><button>");
      out.print( loginUser.getUserName() );
      out.write("</button></li>\r\n");
      out.write("                            <div class=\"mydrop-content\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fas fa-user-circle\"></i>프로필</a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"far fa-envelope\"></i>메시지</a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"far fa-credit-card\"></i>결제내역</a>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <a href=\"/testt/logout\"><i class=\"fa fa-sign-out-alt\"></i>로그아웃</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </div>        \r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"enroll-form\" class=\"modal\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"form-nav\">\r\n");
      out.write("                   <button id=\"login-tab\" class=\"form-tab\" onclick=\"changeTab('form-login', 'login-tab')\">로그인</button>\r\n");
      out.write("                   <button id=\"signup-tab\" class=\"form-tab\" onclick=\"changeTab('form-signup', 'signup-tab')\">회원가입</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-content\" id=\"form-login\">\r\n");
      out.write("                    <button id=\"api-login\"><img src=\"/testt/resources/img/google_logo.png\" alt=\"\">Google로 로그인</button>\r\n");
      out.write("                    <hr><p id=\"center-word\">또는</p><hr>\r\n");
      out.write("                    \r\n");
      out.write("                    <form action=\"/testt/login.ed\" method=\"post\" id=\"login-form\">\r\n");
      out.write("                        <p class=\"placeholder\" id=\"login-email-placeholder\">이메일</p>\r\n");
      out.write("                        <input type=\"text\" id=\"login-email\" name=\"uemail\" autocomplete=off required>\r\n");
      out.write("                        <p class=\"guide\" id=\"login-email-focus\">등록한 이메일 주소를 입력해주세요</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"login-pwd-placeholder\">비밀번호</p>\r\n");
      out.write("                        <input type=\"password\" id=\"login-pwd\" name=\"upwd\" required>\r\n");
      out.write("                        <p class=\"guide\" id=\"login-pwd-focus\">6자 이상, 20자 미만으로 입력해주세요</p>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"form-btn login-btn\" type=\"submit\">이메일로 로그인</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <a href=\"/testt/views/findpwd/findpwd.jsp\">비밀번호를 잊어버렸어요.</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-content\" id=\"form-signup\" style=\"display: none\">\r\n");
      out.write("                    <form action=\"/testt/enroll.ed\" method=\"post\">\r\n");
      out.write("                        <p class=\"placeholder\" id=\"email-placeholder\">이메일</p>\r\n");
      out.write("                        <input type=\"text\" name=\"uemail\" id=\"signup-email\" autocomplete=off required>\r\n");
      out.write("                        <p class=\"guide\" id=\"email-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"pwd-placeholder\">비밀번호</p>\r\n");
      out.write("                        <input type=\"password\" name=\"upwd\" id=\"signup-pwd\" required>\r\n");
      out.write("                        <p class=\"guide\" id=\"pwd-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"pwdchk-placeholder\">비밀번호 확인</p>\r\n");
      out.write("                        <input type=\"password\" id=\"signup-pwdchk\" required>\r\n");
      out.write("                        <p class=\"guide\" id=\"pwdchk-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"placeholder\" id=\"name-placeholder\">이름(실명)</p>\r\n");
      out.write("                        <input type=\"text\" name=\"uname\" id=\"signup-name\" autocomplete=off required>\r\n");
      out.write("                        <p class=\"guide\" id=\"name-focus\">　</p>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"form-btn enroll-btn\" type=\"submit\">이메일로 회원가입</button>\r\n");
      out.write("                        <p>회원가입 시, <a href=\"#\">탈무브 이용약관</a>, <a href=\"#\">개인정보 취급방침</a> 및 <a href=\"#\">개인정보 3자 제공</a>에 동의하게 됩니다.</p>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <input class=\"carousel-open\" type=\"radio\" id=\"carousel-1\" name=\"carousel\" aria-hidden=\"true\" hidden=\"\" checked=\"checked\">\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"resources/img/carousel_1.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input class=\"carousel-open\" type=\"radio\" id=\"carousel-2\" name=\"carousel\" aria-hidden=\"true\" hidden=\"\">\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"resources/img/carousel_2.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input class=\"carousel-open\" type=\"radio\" id=\"carousel-3\" name=\"carousel\" aria-hidden=\"true\" hidden=\"\">\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"resources/img/carousel_3.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <label for=\"carousel-3\" class=\"carousel-control prev control-1\">‹</label>\r\n");
      out.write("            <label for=\"carousel-2\" class=\"carousel-control next control-1\">›</label>\r\n");
      out.write("            <label for=\"carousel-1\" class=\"carousel-control prev control-2\">‹</label>\r\n");
      out.write("            <label for=\"carousel-3\" class=\"carousel-control next control-2\">›</label>\r\n");
      out.write("            <label for=\"carousel-2\" class=\"carousel-control prev control-3\">‹</label>\r\n");
      out.write("            <label for=\"carousel-1\" class=\"carousel-control next control-3\">›</label>\r\n");
      out.write("            <ol class=\"carousel-indicators\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"carousel-1\" class=\"carousel-bullet\">•</label>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"carousel-2\" class=\"carousel-bullet\">•</label>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"carousel-3\" class=\"carousel-bullet\">•</label>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"card-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <h2><span class=\"card-category-sbj\">프로그래밍</span> 분야의 인기 강좌</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>Java 기초부터 심화까지<br><br></h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample_thumbnail2.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>1시간 만에 사이트 만들기<br><br></h4>\r\n");
      out.write("                       <span>By 허태규</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample_thumbnail3.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>10분만에 웹페이지 선물하기<br><br></h4>\r\n");
      out.write("                       <span>By 박건우</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample_thumbnail4.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>모두를 위한 딥러닝 - Reinforcement Learning</h4>\r\n");
      out.write("                       <span>By JiWoo Hwang</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <h2><span class=\"card-category-sbj\">금융</span> 분야의 신규 강좌</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <h2><span class=\"card-category-sbj\">금융</span> 분야의 최근 수강된 강좌</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm lecture-main\">\r\n");
      out.write("                    <a href=\"#\"><img class=\"thumbnail\" src=\"resources/img/sample%20thumbnail.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"row lecture-header\">\r\n");
      out.write("                       <h4>쉽게 배우는 해운 시황의 이해</h4>\r\n");
      out.write("                       <span>By 이학열</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row lecture-footer\">\r\n");
      out.write("                        <span class=\"starpoint\">★☆☆☆☆</span>\r\n");
      out.write("                        <span class=\"point\">1.0(12)</span>\r\n");
      out.write("                        <span class=\"price\">￦14,000</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"section-interview\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <h2>수강생 인터뷰</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm\">\r\n");
      out.write("                <blockquote>\r\n");
      out.write("                    탈무브를 통해 저의 새로운 적성을 탐색하는데 도움을 받을 수 있었습니다. 또 다른 강좌가 개설된다면 기꺼이 수강할 의향이 있습니다! 항상 노력하는 강사분과 탈무브에 감사합니다!\r\n");
      out.write("                    <cite><img src=\"resources/img/customer-1.jpg\">Lee Hack Yeol</cite>\r\n");
      out.write("                </blockquote>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm\">\r\n");
      out.write("                <blockquote>\r\n");
      out.write("                    유튜브에서 보던 유사 콘텐츠들보다 더 자세하고 체계적으로 설명해주셔서 따라가기 좋았어요. 단순한 기능 따라 하기가 아니라 적절한 비유에 따른 설명으로 이해가 너무 수월했습니다!\r\n");
      out.write("                    <cite><img src=\"resources/img/customer-2.jpg\">Hwang Ji Woo</cite>\r\n");
      out.write("                </blockquote>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm\">\r\n");
      out.write("                <blockquote>\r\n");
      out.write("                    마흔 중반이 넘어서야 경제와 주식 공부를 하고 있습니다. 저 같은 사람에게는 사막의 오아시스와 같은 단비가 되는 것 같습니다. 이렇게 좋은 강의 기획 해주신 강사분들에게 감사를 표합니다.\r\n");
      out.write("                    <cite><img src=\"resources/img/customer-3.jpg\">Michael Cho</cite>\r\n");
      out.write("                </blockquote>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t    <div class=\"footer-container pt-2\">\r\n");
      out.write("\t        <div class=\"row footer-top\">\r\n");
      out.write("\t            <div class=\"col-12 col-md-6 footer-top-left\">\r\n");
      out.write("\t                <p class=\"logo-text\">TALMOVE</p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"col-6 col-md-6 footer-top-right\">\r\n");
      out.write("\t                <ul class=\"footer-nav mt-3\">\r\n");
      out.write("\t                    <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("\t                    <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("\t                </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"row footer-middle mt-4\">\r\n");
      out.write("\t            <p class=\"col-sm-12\">서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층, 3층, 4층<br>010-1234-5678</p>\r\n");
      out.write("\t            \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"row footer-bottom\">\r\n");
      out.write("\t            <p class=\"col-sm-12\">Copyright &copy; 2019 by TALMOVE. All rights reserved.</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("    \r\n");
      out.write("    <button onclick=\"setTimeout(topFunction(), 200);\" id=\"topBtn\" title=\"Go to Top\"><i class=\"fas fa-chevron-up\"></i></button>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <script type=\"text/javascript\" src=\"vendors/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
